feat: track store r/w consume for enabling plain store
bnb-chain/greenfield-cosmos-sdk pull request #269
Opened 2023-08-11 08:34 UTC by forcodedancing

### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes:
* add each change in a bullet point here
* ...

2023-08-11 09:52 UTC, guagualvcha approved these changes

2023-08-14 03:24 UTC, guagualvcha commented on baseapp/abci.go
> +	proto.Unmarshal(result.Data, msgData)
can we not do `Unmarshal` and `marshal` here, as it is duplicated calculation, is it possible to achieve it in  `makeABCIData`?

2023-08-14 03:29 UTC, guagualvcha commented on baseapp/abci.go
> +	proto.Unmarshal(result.Data, msgData)
Not only tx need this `RwUsed`, but also begin block  and end block.

2023-08-14 03:30 UTC, guagualvcha commented on baseapp/baseapp.go
> -	// queryState is set on InitChain and BeginBlock
why delete this?

2023-08-14 03:31 UTC, guagualvcha commented on baseapp/baseapp.go
> +	enablePlainStore bool
`enablePlainStore` means the `skipAppHashVerify` should be true, any way to verify they are consistent?

2023-08-14 03:32 UTC, guagualvcha commented on baseapp/baseapp.go
> +	enablePlainStore bool
also highlight the impaction of this configure.

2023-08-14 03:33 UTC, guagualvcha commented on baseapp/baseapp.go
> +			if !app.fauxMerkleMode && !app.enablePlainStore {
please use `IsIavlStore` instead?

2023-08-14 03:33 UTC, guagualvcha commented on baseapp/baseapp.go
> +		if !app.fauxMerkleMode && !app.enablePlainStore {
use `IsIavlStore` instead?

2023-08-14 03:39 UTC, guagualvcha commented on types/context.go
> +	return gaskv.NewStore(c.ms.GetKVStore(key), c.gasMeter, c.kvGasConfig)
I prefer `	return gaskv.NewStore(c.MultiStore().GetKVStore(key), c.gasMeter, c.kvGasConfig)`

2023-08-14 03:39 UTC, guagualvcha commented on types/context.go
> +	return gaskv.NewStore(c.ms.GetKVStore(key), c.gasMeter, c.kvGasConfig)
prefer `return gaskv.NewStore(c.MultiStore().GetKVStore(key), c.gasMeter, c.kvGasConfig)`

2023-08-14 03:40 UTC, guagualvcha requested changes
need add more gasrw for endblock and begin block.

2023-08-14 03:42 UTC, forcodedancing commented on baseapp/baseapp.go
> -	// queryState is set on InitChain and BeginBlock
It is duplicated comment. There is same comment in the following line.

2023-08-14 05:45 UTC, forcodedancing commented on types/context.go
> +	return gaskv.NewStore(c.ms.GetKVStore(key), c.gasMeter, c.kvGasConfig)
updated

2023-08-14 05:45 UTC, forcodedancing commented on types/context.go
> +	return gaskv.NewStore(c.ms.GetKVStore(key), c.gasMeter, c.kvGasConfig)
updated

2023-08-14 05:45 UTC, forcodedancing commented on baseapp/baseapp.go
> +		if !app.fauxMerkleMode && !app.enablePlainStore {
updated

2023-08-14 05:45 UTC, forcodedancing commented on baseapp/baseapp.go
> +			if !app.fauxMerkleMode && !app.enablePlainStore {
updated

2023-08-15 07:20 UTC, forcodedancing commented on baseapp/baseapp.go
> +	enablePlainStore bool
added some comments to app.toml

2023-08-15 11:46 UTC, guagualvcha commented on baseapp/abci.go
> +		ctx = ctx.WithGasMeter(sdk.NewInfiniteGasMeter())
what kind of `GasMeter` are we using during the block execution? if use `basicGasMeter`, may cause `ErrorOutOfGas`

2023-08-15 12:05 UTC, guagualvcha approved these changes

2023-08-16 01:39 UTC, merged