feat: support eip712 private keys import
bnb-chain/greenfield-cosmos-sdk pull request #357
Opened 2023-11-02 08:43 UTC by j75689

### Description

feat: support eip712 private keys import

### Rationale

support eip712 private keys import via cmd

### Example

```bash
./build/bin/gnfd keys import testing 89319801b3f2d5cb... --home ./.local --eip712-private-key --keyring-backend test
./build/bin/gnfd keys list --home ./.local --keyring-backend test
```

<img width="929" alt="image" src="https://github.com/bnb-chain/greenfield-cosmos-sdk/assets/25412254/1959cf0b-de22-46b3-ab10-62906a0eddce">

### Changes

Notable changes:
* cmd

2023-11-02 08:47 UTC, zjubfd approved these changes

2023-11-02 08:48 UTC, zjubfd commented on client/keys/import.go
> +		Long:  "Import a ASCII armored/EIP-712 private key into the local keybase.",
I think EIP-712 can not describe a kind of private key

2023-11-02 08:48 UTC, zjubfd requested changes
change the description

2023-11-02 08:56 UTC, j75689 commented on client/keys/import.go
> +		Long:  "Import a ASCII armored/EIP-712 private key into the local keybase.",
updated

2023-11-09 07:14 UTC, zjubfd approved these changes

2023-11-09 07:14 UTC, merged